# Generated by Django 4.0.1 on 2022-02-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_assignment_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='voulenteer',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='voulenteer',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
